cassandra user_types_test.py::TestUserTypes::test_no_counters_in_user_types false true
log_dst_dir = /users/masix/vm_images/ZebraConf/app_meta/logs
the_test is user_types_test.py::TestUserTypes::test_no_counters_in_user_types
rm: cannot remove '/tmp/my_log.txt': No such file or directory
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /users/masix/dtest/bin/python3
cachedir: .pytest_cache
rootdir: /users/masix/cassandra-dtest, inifile: pytest.ini
plugins: timeout-1.4.2, repeat-0.9.1, flaky-3.7.0
timeout: 1200.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

user_types_test.py::TestUserTypes::test_no_counters_in_user_types PASSED [100%]
===Flaky Test Report===

test_no_counters_in_user_types passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

=========================== 1 passed in 8.26 seconds ===========================
[msx] rc = 0
mv /tmp/my_log.txt /users/masix/vm_images/ZebraConf/app_meta/logs/user_types_test.py::TestUserTypes::test_no_counters_in_user_types-output_1643089345470_2759332701.txt
