mesg: ttyname failed: Inappropriate ioctl for device
cassandra batch_test.py::TestBatch::test_unlogged_batch_rejects_counter_mutations false true
log_dst_dir = /root/vm_images/ZebraConf/app_meta/logs
the_test is batch_test.py::TestBatch::test_unlogged_batch_rejects_counter_mutations
rm: cannot remove '/tmp/my_log.txt': No such file or directory
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /root/dtest/bin/python
cachedir: .pytest_cache
rootdir: /root/cassandra-dtest, inifile: pytest.ini
plugins: flaky-3.7.0, timeout-1.4.2, repeat-0.9.1
timeout: 1200.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

batch_test.py::TestBatch::test_unlogged_batch_rejects_counter_mutations PASSED [100%]
===Flaky Test Report===

test_unlogged_batch_rejects_counter_mutations passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 11.58 seconds ===========================
[msx] rc = 0
mv /tmp/my_log.txt /root/vm_images/ZebraConf/app_meta/logs/batch_test.py::TestBatch::test_unlogged_batch_rejects_counter_mutations-output_1644049433419_1148220048.txt
