mesg: ttyname failed: Inappropriate ioctl for device
cassandra replication_test.py::TestSnitchConfigurationUpdate::test_rf_expand_property_file_snitch false true
log_dst_dir = /root/vm_images/ZebraConf/app_meta/logs
the_test is replication_test.py::TestSnitchConfigurationUpdate::test_rf_expand_property_file_snitch
rm: cannot remove '/tmp/my_log.txt': No such file or directory
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /root/dtest/bin/python
cachedir: .pytest_cache
rootdir: /root/cassandra-dtest, inifile: pytest.ini
plugins: flaky-3.7.0, timeout-1.4.2, repeat-0.9.1
timeout: 1200.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

replication_test.py::TestSnitchConfigurationUpdate::test_rf_expand_property_file_snitch 
-------------------------------- live log call ---------------------------------
09:01:31,966 cassandra.cluster WARNING Host 127.0.0.2:9042 has been marked down
09:01:32,975 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 2.26 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
09:01:35,284 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 3.56 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
09:01:38,895 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 7.04 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
09:01:39,982 cassandra.cluster WARNING Host 127.0.0.3:9042 has been marked down
09:01:41,3 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.3:9042, scheduling retry in 1.84 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
09:01:42,908 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.3:9042, scheduling retry in 4.56 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
09:01:46,17 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 14.24 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
09:01:47,521 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.3:9042, scheduling retry in 8.4 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
09:01:55,943 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.3:9042, scheduling retry in 18.4 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
09:02:00,357 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 29.76 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
09:02:14,392 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.3:9042, scheduling retry in 28.16 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
PASSED                                                                   [100%]
===Flaky Test Report===

test_rf_expand_property_file_snitch passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 105.91 seconds ==========================
[msx] rc = 0
mv /tmp/my_log.txt /root/vm_images/ZebraConf/app_meta/logs/replication_test.py::TestSnitchConfigurationUpdate::test_rf_expand_property_file_snitch-output_1644051774580_456321170.txt
