cassandra write_failures_test.py::TestMultiDCWriteFailures::test_oversized_mutation true true
log_dts_dir = /users/masix/vm_images/ZebraConf/app_meta/logs
the_test is write_failures_test.py::TestMultiDCWriteFailures::test_oversized_mutation
rm: cannot remove '/tmp/my_log.txt': No such file or directory
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /users/masix/dtest/bin/python
cachedir: .pytest_cache
rootdir: /users/masix/cassandra-dtest, inifile: pytest.ini
plugins: flaky-3.7.0, timeout-1.4.2, repeat-0.9.1
timeout: 900.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

write_failures_test.py::TestMultiDCWriteFailures::test_oversized_mutation 
-------------------------------- live log call ---------------------------------
03:28:40,920 ccmlib.node WARNING [msx] ccmlib:node.py:start(), self.name= node1, self.pid= None
03:28:40,922 ccmlib.cluster WARNING [msx] ccmlib:cluster.py:start() p.pid= 6559 node.name= node1 node.pid= None
03:28:41,403 ccmlib.node WARNING [msx] ccmlib:node.py:start(), self.name= node2, self.pid= None
03:28:41,404 ccmlib.cluster WARNING [msx] ccmlib:cluster.py:start() p.pid= 7002 node.name= node2 node.pid= None
03:28:41,855 ccmlib.node WARNING [msx] ccmlib:node.py:start(), self.name= node3, self.pid= None
03:28:41,856 ccmlib.cluster WARNING [msx] ccmlib:cluster.py:start() p.pid= 7464 node.name= node3 node.pid= None
03:28:42,303 ccmlib.node WARNING [msx] ccmlib:node.py:start(), self.name= node4, self.pid= None
03:28:42,304 ccmlib.cluster WARNING [msx] ccmlib:cluster.py:start() p.pid= 7920 node.name= node4 node.pid= None
PASSED                                                                   [100%]
===Flaky Test Report===

test_oversized_mutation passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 34.33 seconds ===========================
[msx] rc = 0
