cassandra auth_join_ring_false_test.py::TestAuth::test_list_users true true
the_test is auth_join_ring_false_test.py::TestAuth::test_list_users
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /users/masix/dtest/bin/python
cachedir: .pytest_cache
rootdir: /users/masix/cassandra-dtest, inifile: pytest.ini
plugins: timeout-1.4.2, repeat-0.9.1, flaky-3.7.0
timeout: 900.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

auth_join_ring_false_test.py::TestAuth::test_list_users 
-------------------------------- live log call ---------------------------------
17:38:05,863 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
17:38:05,950 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node1
17:38:05,950 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
17:38:06,19 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node1
17:38:06,19 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
17:38:22,532 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
17:38:22,627 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node2
17:38:22,627 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
17:38:22,720 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node2
17:38:22,720 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
PASSED                                                                   [100%]
===Flaky Test Report===

test_list_users passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 33.98 seconds ===========================
[msx] rc = 0
