cassandra transient_replication_ring_test.py::TestTransientReplicationRing::test_move_forwards_between_and_cleanup true true
the_test is transient_replication_ring_test.py::TestTransientReplicationRing::test_move_forwards_between_and_cleanup
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /users/masix/dtest/bin/python
cachedir: .pytest_cache
rootdir: /users/masix/cassandra-dtest, inifile: pytest.ini
plugins: timeout-1.4.2, repeat-0.9.1, flaky-3.7.0
timeout: 900.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

transient_replication_ring_test.py::TestTransientReplicationRing::test_move_forwards_between_and_cleanup 
-------------------------------- live log setup --------------------------------
15:27:34,965 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
15:27:35,51 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node1
15:27:35,51 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
15:27:35,122 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node1
15:27:35,122 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
15:27:35,216 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
15:27:35,301 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node2
15:27:35,301 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
15:27:35,369 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node2
15:27:35,369 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
15:27:35,464 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
15:27:35,548 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node3
15:27:35,549 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
15:27:35,617 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node3
15:27:35,617 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
-------------------------------- live log call ---------------------------------
15:27:55,797 ccmlib.node WARNING [msx] ccmlib:copy_config_files.py, conf_dir = /users/masix/cassandra/conf
15:27:55,892 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node4
15:27:55,892 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
15:27:55,968 ccmlib.node WARNING [msx] ccmlib:node.py, self.name = node4
15:27:55,968 ccmlib.node WARNING [msx] ccmlib:node.py, sstable_preemptive_open_interval_in_mb = 50
15:29:02,853 cassandra.cluster WARNING Host 127.0.0.2:9042 has been marked down
15:29:03,961 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 1.76 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
15:29:05,767 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 4.6 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
15:29:10,381 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 8.64 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
15:29:19,109 cassandra.pool WARNING Error attempting to reconnect to 127.0.0.2:9042, scheduling retry in 17.76 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
PASSED                                                                   [100%]
===Flaky Test Report===

test_move_forwards_between_and_cleanup passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 167.83 seconds ==========================
[msx] rc = 0
